name: XY Malloc
on: [push, pull_request, release]
jobs:
  check_env:
    name: Check Environments
    runs-on: ubuntu-latest
    steps:
      - run: gcc --version
      - run: cmake --version
      - run: df -h
      - run: free -h
      - run: sudo apt-get install -y libnuma-dev
  run_test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: mkdir build
      - run: cd build && cmake .. && make huge_page -Wall
      - run: ./build/huge_page

